### DISCUSSION TITLE
v1.0.0-next.36

### DISCUSSION THREAD

**Discussion by sastan** [tw-in-js/twind#288] [General]
a new pre-release is availabe: 1.0.0-next.36

## @twind/preset-ext

-   feat: add descendants selector using `_` eg `&_span:underline`; can be combined with other selectors `&_h1>span~a:underline` ([`cbd37a10`](https://github.com/tw-in-js/twind/commit/cbd37a107038d9c025b24ba24a24b49b49f101b8))
-   fix: group/peer hocus named group regex ([`8f1288a0`](https://github.com/tw-in-js/twind/commit/8f1288a049969a0dbb2402ae0f6212d726ddec5b))

## @twind/preset-tailwind

-   refactor: move hashing of vars (`--tw-<...>`) from preset-tailwind into core — this allows var hashing without the tailwind preset ([`ae979d12`](https://github.com/tw-in-js/twind/commit/ae979d12fe01cfed32c44eea23ef8a9f2d983eae))
-   Add missing height properties max/min/fit-content ([#285](https://github.com/tw-in-js/twind/pull/285)) 🙏🏽 [@IgnusG](https://github.com/IgnusG)!
-   fix: use `text-decoration-line` ([`346efc4e`](https://github.com/tw-in-js/twind/commit/346efc4e84042d043e17bac8d829f0408279448e))

## @twind/preset-tailwind-forms

-   fix: use `text-decoration-line` ([`346efc4e`](https://github.com/tw-in-js/twind/commit/346efc4e84042d043e17bac8d829f0408279448e))

## @twind/preset-typography

-   feat: add @twind/preset-typography ([`e3796bf9`](https://github.com/tw-in-js/twind/commit/e3796bf9788373a33214a23bdaba6f56b9feaf96))
-   fix: use `text-decoration-line` ([`346efc4e`](https://github.com/tw-in-js/twind/commit/346efc4e84042d043e17bac8d829f0408279448e))

## twind

-   relax some typings where the actual generic type does not matter ([`28cbaef5`](https://github.com/tw-in-js/twind/commit/28cbaef54f226e7542e9197b0dab69e55f588806))
-   fix: ensure colors DEFAULT values override nested objects ([`43d61076`](https://github.com/tw-in-js/twind/commit/43d610769152aef2943383b3a2574b9be01acc49))
-   refactor: include full precendence in resume data ([`80ce410a`](https://github.com/tw-in-js/twind/commit/80ce410a60892ba70fa8805a37aa89f0dbc13c7d))
-   fix: move styles generated by `animation()` into `components` layer — this allows to override animation properties using utilities ([`39b45125`](https://github.com/tw-in-js/twind/commit/39b451256c10bd6f82f45015effbefb41aee8a76))
-   feat: auto dark colors ([`2f8f69d2`](https://github.com/tw-in-js/twind/commit/2f8f69d27531fad4346af57f0fef3f473d2c6ee3))

    If enabled, automatic dark colors are generated for each light color (eg no `dark:` variant is present). This feature is opt-in and twind provides a builtin function that works with [tailwind color palettes](https://tailwindcss.com/docs/customizing-colors) (`50`, `100`, `200`, ..., `800`, `900`).

    ```ts
    import { autoDarkColor } from 'twind'

    defineConfig({
      // for tailwind color palettes: 50 -> 900, 100 -> 800, ..., 800 -> 100, 900 -> 50
      darkColor: autoDarkColor,
      // other possible implementations
      darkColor: (section, key, { theme }) => theme(`${section}.${key}-dark`) as ColorValue,
      darkColor: (section, key, { theme }) => theme(`dark.${section}.${key}`) as ColorValue,
      darkColor: (section, key, { theme }) => theme(`${section}.dark.${key}`) as ColorValue,
      darkColor: (section, key, context, lightColor) => generateDarkColor(lightColor),
    })
    ```

    Example css for `text-gray-900`:

    ```css
    .text-gray-900 {
      --tw-text-opacity: 1;
      color: rgba(15, 23, 42, var(--tw-text-opacity));
    }
    @media (prefers-color-scheme: dark) {
      .text-gray-900 {
        --tw-text-opacity: 1;
        color: rgba(248, 250, 252, var(--tw-text-opacity));
      }
    }
    ```

    The auto-generated dark color can be overridden by the usual `dark:...` variant: `text-gray-900 dark:text-gray-100`.

    ```css
    .text-gray-900 {
      --tw-text-opacity: 1;
      color: rgba(15, 23, 42, var(--tw-text-opacity));
    }
    @media (prefers-color-scheme: dark) {
      .text-gray-900 {
        --tw-text-opacity: 1;
        color: rgba(248, 250, 252, var(--tw-text-opacity));
      }
    }
    @media (prefers-color-scheme: dark) {
      .dark\\:text-gray-100 {
        --tw-text-opacity: 1;
        color: rgba(241, 245, 249, var(--tw-text-opacity));
      }
    }
    ```

-   fix: handle color function in replacement for `theme(...)` ([`9fc5baec`](https://github.com/tw-in-js/twind/commit/9fc5baeca6031d27ac81402b0e614d01c3cd20e7))
-   fix: always use rgba color ([`aaad7e44`](https://github.com/tw-in-js/twind/commit/aaad7e4426068a55b00e23df2e084cfc8a46b2ca))
-   refactor: move hashing of vars (`--tw-<...>`) from preset-tailwind into core — this allows var hashing without the tailwind preset ([`ae979d12`](https://github.com/tw-in-js/twind/commit/ae979d12fe01cfed32c44eea23ef8a9f2d983eae))
-   fix: prevent double class name hashing ([`fc9b0c27`](https://github.com/tw-in-js/twind/commit/fc9b0c277f26e0fc1aad693bd13a80d50b27c71c))
-   fix: use `text-decoration-line` ([`346efc4e`](https://github.com/tw-in-js/twind/commit/346efc4e84042d043e17bac8d829f0408279448e))
-   fix: ensure theme returns all sections ([`8bbc2a42`](https://github.com/tw-in-js/twind/commit/8bbc2a426054cedc705392eb51aebf0029547d67))
-   fix: use same color section detection ([`8dfd105b`](https://github.com/tw-in-js/twind/commit/8dfd105bf0b10d82e3d024b6a318a4b7e6064d90))

## @twind/with-next

-   relax some typings where the actual generic type does not matter ([`28cbaef5`](https://github.com/tw-in-js/twind/commit/28cbaef54f226e7542e9197b0dab69e55f588806))

<hr /><em>This discussion was created from the release <a href='https://github.com/tw-in-js/twind/releases/tag/v1.0.0-next.36'>v1.0.0-next.36</a>.</em>
