### ISSUE TITLE
Using `scale-0` without `transform` will cause shifting layout when nested inside parent with `translate`.

### ISSUE THREAD

**Issue by rockmandash** [tw-in-js/twind#158]
https://github.com/tw-in-js/twind/blob/3b8709c98d99befa533abb60485638214f0db175/docs/getting-started/browser-support.md#L15

I don't know if I can use `scale-0` without `transform` standalone, but the docs seem to say **yes** to this case, and it's working in the latest Twind, so I found a weird situation when not using `transform`.

Please see this minimum example:

# Normal Version

```html
<div class="flex justify-center items-center h-screen">
  <div class="p-8 shadow transform -translate-x-32">
    <div id="animated-circle" class="transform w-4 h-4 bg-indigo-500 rounded-full transition-transform"></div>
  </div>
</div>

<script type="module" src="https://cdn.skypack.dev/twind/shim"></script>
```

```js
setInterval(() => {
  const elem = document.getElementById("animated-circle");

  if (elem) {
    elem.classList.toggle("scale-0");
  }
}, 1500);
```

https://user-images.githubusercontent.com/7580792/112451908-f8912180-8d90-11eb-9bed-7cbed36692fc.mov

## Without `transform` class

![image](https://user-images.githubusercontent.com/7580792/112452302-73f2d300-8d91-11eb-80f5-eff7a14c07bb.png)

https://user-images.githubusercontent.com/7580792/112452331-7ce3a480-8d91-11eb-9e4d-39d8a70a0012.mov

Codepen: https://codepen.io/rockmandash/pen/abpvaxq

**If using the transform-related class will have to have the `transform` class, then this issue can be ignored.**

**Comment by sastan** [comment]
The issue comes from the `-translate-x-32` on the parent element. It sets the `--tw-translate-x` custom property. When adding `translate` that property is reset. If no `translate` it is used it inherits this `--tw-translate-x` value from the parent element.

```css
.transform {
  /* reset properties */
  --tw-translate-x: 0;
  --tw-translate-y: 0;
  --tw-rotate: 0;
  --tw-skew-x: 0;
  --tw-skew-y: 0;
  --tw-scale-x: 1;
  --tw-scale-y: 1;
  transform:
    translateX(var(--tw-translate-x,0))
    translateY(var(--tw-translate-y,0))
    rotate(var(--tw-rotate,0))
    skewX(var(--tw-skew-x,0))
    skewY(var(--tw-skew-y,0))
    scaleX(var(--tw-scale-x,1))
    scaleY(var(--tw-scale-y,1));
}

.-translate-x-32 {
  --tw-translate-x: calc(8rem * -1);
}
```

This is implemented like tailwindcs does it. But I think we should switch to how `--tw-shadow` works:

```css
/* reset on every element */
* {
  --tw-translate-x: 0;
  --tw-translate-y: 0;
  --tw-rotate: 0;
  --tw-skew-x: 0;
  --tw-skew-y: 0;
  --tw-scale-x: 1;
  --tw-scale-y: 1;
}

.transform {
  transform:
    translateX(var(--tw-translate-x,0))
    translateY(var(--tw-translate-y,0))
    rotate(var(--tw-rotate,0))
    skewX(var(--tw-skew-x,0))
    skewY(var(--tw-skew-y,0))
    scaleX(var(--tw-scale-x,1))
    scaleY(var(--tw-scale-y,1));
}

.-translate-x-32 {
  --tw-translate-x: calc(8rem * -1);
}
```

https://codepen.io/sastan/pen/PoWPyKZ
