### ISSUE TITLE
grid-cols-[valuesxxx] not working/compiling properly

### ISSUE THREAD

**Issue by jd-0001** [tw-in-js/twind#202]
`grid-cols-[auto,480px]` isn't working in twind. However, it is working in Tailwind & WindiCSS.

Below is a comparison of how it is getting compiled in tailwind & windi vs in twind.

Windi & Tailwind:

```css
.grid-cols-\[auto\2c 480px\] {
    grid-template-columns: auto 480px;
}
```

vs Twind

```csss
.grid-cols-\[auto\,480px\] {
}
```
