### ISSUE TITLE
apply function unable to take effect on multiple classes while doing a preflight override

### ISSUE THREAD

**Issue by nimser** [tw-in-js/twind#227]
Using the `apply` function with multiple class names when calling `setup` for performing preflight overrides, as in this simple example:

```javascript
setup({
    preflight: preflight => css(
        preflight,
        { h1: apply`text-2xl mb-4` }
      )
```
causes unexpected outcome. Some combinations of classes won't work, as in, adding a second class to `apply` may prevent the first class to function.

[A minimal reproducible example is provided in this interactive REPL](https://svelte.dev/repl/43e3a29fd26d4f7797add822c7c75d7b?version=3.44.2). Notice how removing the `mb-4` class in the `apply` function of this example will provide the expected outcome, but keeping `mb-4` in does not keep styles for `text-2xl`.

This is true whether the `css` function is used or not (e.g. ```preflight => ({...preflight, h1: apply`text-2xl mb-4`})``` and ```preflight => css(preflight,{ h1: apply`text-2xl mb-4`})``` will produce the same outcome)

**Comment by sastan** [comment]
The problem does not seem to be with `@apply`. The generated style for `h1` includes the bottom margin:

```css
h1 {
  font-size: 1.5rem;
  line-height: 2rem;
  margin-bottom: 1rem;
}
```

The problem is with the order of the styles within the stylesheet. In twind we sort the generated style rules by the number of declarations (and other things are considered as well). In this case the preflight h1 wins because it has only one rule `margin: 0px;` which is considered more important than the one you given. The reason is that we assume that a rule with less declarations overwrites a rule with more declaration (eg CSS variables and other compound rules).

For your example that leads to the following effective styles:

![effective styles](https://user-images.githubusercontent.com/514405/145194874-0c6c5fe9-6861-4c5b-b888-3ce924dcfa4e.png)

This can be fixed by increasing the [specificity](https://specificity.keegan.st) of your `h1`.

```js
setup({
  preflight: preflight => ({
    ...preflight,
    body: {
       h1: apply`text-2xl mb-4`
    }
  })
})
```

Which would lead to ([repl](https://svelte.dev/repl/aa1c9455acaa48c7bbe6217c3945934e?version=3.44.2)):

![increased specificity styles](https://user-images.githubusercontent.com/514405/145195199-cf855b11-3d2e-4cb6-83df-2669be96627d.png)

**Comment by nimser** [comment]
> The problem is with the order of the styles within the stylesheet. In twind we sort the generated style rules by the number of declarations (and other things are considered as well). In this case the preflight h1 wins because it has only one rule `margin: 0px;` which is considered more important than the one you given. The reason is that we assume that a rule with less declarations overwrites a rule with more declaration (eg CSS variables and other compound rules).

Interesting, seems like a non-trivial assumption that has big implications on how styles get rendered. I guess having to make these kind of assumptions is a drawback of using css-in-js solutions as opposed to native Tailwind?

However, could you explain why the preflight rule wins when I apply both the `text-2xl` and `mb-10` classes, but that my new rule is effective when I apply only `text-2xl`?

Thank you for all the clarifications.

**Comment by sastan** [comment]
> Interesting, seems like a non-trivial assumption that has big implications on how styles get rendered. I guess having to make these kind of assumptions is a drawback of using css-in-js solutions as opposed to native Tailwind?

The assumptions work pretty well except for the preflight. For example `mb-2` should override `m-0` or all color classes arr setting an opacity variable which may be overridden by an opacity class.

Native tailwind has the order defined by generating all styles and purging after wards. The JIT has basically the same order rules as twind because it generates the styles on demand and needs to ensure they are generated in a predictable order.

> However, could you explain why the preflight rule wins when I apply both the `text-2xl` and `mb-10` classes, but that my new rule is effective when I apply only `text-2xl`?

If you only use `text-2xl` the following styles are generated (last one wins):

```css
h1, h2, h3, h4, h5, h6 {
  font-size: inherit;
  font-weight: inherit;
}

h1 {
  font-size: 1.5rem;
  line-height: 2rem;
}

body, blockquote, dl, dd, h1, h2, h3, h4, h5, h6, hr, figure, p, pre, fieldset, ol, ul {
  margin: 0px;
}
```

As you see the `h1` is after `h1, h2, h3, h4, h5, h6` and therefore overwrites `font-size`.

As soon as we add another class like `mb-2` or `underline` the order will change:

```css
h1 {
  font-size: 1.5rem;
  line-height: 2rem;
  margin-bottom: 0.5rem;
}

h1, h2, h3, h4, h5, h6 {
  font-size: inherit;
  font-weight: inherit;
}

body, blockquote, dl, dd, h1, h2, h3, h4, h5, h6, hr, figure, p, pre, fieldset, ol, ul {
  margin: 0px;
}
```

This is because `h1` now has 3 declarations and is therefore considered less specific than the other rules.

This could be solved by using `:where()` (zero specificity) for all default preflight rules. But sadly the [browser support](https://caniuse.com/mdn-css_selectors_where) is not as good yet.

Another alternative I'm thinking about is to change how `apply` works. Instead of merging all classes into one rule we generate a rule for each class. This would align more with how classes are applied outside of `apply`. The generated styles would be like this:

```css
h1, h2, h3, h4, h5, h6 {
  font-size: inherit;
  font-weight: inherit;
}

h1 {
  font-size: 1.5rem;
  line-height: 2rem;
}

body, blockquote, dl, dd, h1, h2, h3, h4, h5, h6, hr, figure, p, pre, fieldset, ol, ul {
  margin: 0px;
}

h1 {
  margin-bottom: 0.5rem;
}
```

> Thank you @sastan for all the clarifications.

I hope that helps.

> Edit: I think users would greatly benefit from having both the `body: {...}` pattern and the ordering rules about how styles are generated, explained in the documentation.

Yes. Definitly.
