### ISSUE TITLE
Duplicate `color` properties when prerendering

### ISSUE THREAD

**Issue by rschristian** [tw-in-js/twind#236]
Noticed this when using `@twind/wmr`, and the [WMR Example](https://github.com/tw-in-js/example-wmr) replicates this behavior. I don't believe this is specific to the WMR or Preact integrations, so opening here.

It seems that using ~~`getStyleTag()`~~ (Edit: `getStyleTag()` seems to be okay, my test was bad) results in colors being duplicated: once in hex, and another as `rgba()`. As far as I can tell this serves no purpose, though maybe that's incorrect?

For example, in the linked WMR project, after a build (`yarn/npm run build`) you can spot the following in the output HTML (prettified):

```css
.text-white {
  --tw-text-opacity: 1;
  color: #fff;
  color: rgba(255,255,255,var(--tw-text-opacity));
}
```
It's not a huge amount of extra bytes, but isn't ideal either as I don't believe it will ever be used. This isn't isolated to `color`, `background-color` and `border-color` are also affected in my quick test. Happens to both custom colors as well as defaults.
