### ISSUE TITLE
[Feature Request] - Expand preset-ext arbitrary nested selectors variant

### ISSUE THREAD

**Issue by tylerforesthauser** [tw-in-js/twind#294]
So it seems I've opened a can of worms digging into this but I think I've finally come up with a proposal that makes sense. 

You've already got support for `type` and `universal` selectors, so it comes down to `class`, `id` and `attribute` selectors. I think this variant would gain immeasurable power with the added support of just `attribute` selectors. This would ultimately allow for a way to target nested elements by class, id as well as whatever attribute a user desires. They would, however, benefit from comprehensive syntax support.

Here are some examples of possible selectors and the working CSS output. I am not clever enough to know how the regex would work for these...

LINKS - https://codepen.io/tylerforesthauser/pen/dyZJZGx
```css
/* &_a:text-blue-500 */
.\&_a a {
  color: #3b82f6;
}

/* Internal links, beginning with "#" */
/* &_a[href^='#']:bg-yellow-500 */
.\&_a\[href\^\=\'\#\'\]\:bg-yellow-500 a[href^="#"] {
  background-color: #eab308;
}

/* Links with "example" anywhere in the URL */
/* &_a[href*='example']:bg-slate-300 */
.\&_a\[href\*\=\'example\'\]\:bg-slate-300 a[href*="example"] {
  background-color: #cbd5e1;
}

/* Links with "insensitive" anywhere in the URL, regardless of capitalization */
/* &_a[href*='insensitive'_i]:text-cyan-300 */
.\&_a\[href\*\=\'insensitive\'_i\]\:text-cyan-300 a[href*="insensitive" i] {
  color: #67e8f9;
}

/* Links with "cAsE" anywhere in the URL, with matching capitalization */
/* &_a[href*='cAsE'_s]:text-pink-400 */
.\&_a\[href\*\=\'cAsE\'_s\]\:text-pink-400 a[href*="cAsE" s] {
  color: #f472b6;
}

/* Links that end in ".org" */
/* &_a[href$='.org']:text-red-500 */
.\&_a\[href\$\=\'\.org\'\]\:text-red-500 a[href$=".org"] {
  color: #f43f5e;
}

/* Links that start with "https" and end in ".org" */
/* &_a[href^='https'][href$='.org']:text-green-500 */
.\&_a\[href\^\=\'https\'\]\[href\$\=\'\.org\'\]\:text-green-500
  a[href^="https"][href$=".org"] {
  color: #22c55e;
}
```

LANGUAGES - https://codepen.io/tylerforesthauser/pen/BamJYNe
```css
/* All divs with a `lang` attribute are bold. */
/* &_div[lang]:bold */
.\&_div\[lang\] div[lang] {
  font-weight: bold;
}

/* All divs without a `lang` attribute are italicized. */
/* &_div:not([lang]):italic */
.\&_div\:not\(\[lang\]\)\:italic div:not([lang]) {
  font-style: italic;
}

/* All divs in US English are blue. */
/* &_div[lang~='en-us']:text-blue-500 */
.\&_div\[lang\~\=\'en-us\'\]\:text-blue-500 div[lang~='en-us'] {
  color: #3b82f6;
}

/* All divs in Portuguese are green. */
/* &_div[lang='pt']:text-green-500 */
.\&_div\[lang\=\'pt\'\]\:text-green-500 div[lang='pt'] {
  color: #22c55e;
}

/* All divs in Chinese are red, whether simplified (zh-CN) or traditional (zh-TW). */
/* &_div[lang|='zh']:text-red-500 */
.\&_div\[lang\|\=\'zh\'\]\:text-red-500 div[lang|='zh'] {
  color: red;
}

/* All divs with a Traditional Chinese `data-lang` are purple. */
/* Note: You could also use hyphenated attributes without double quotes */
/* &_div[data-lang='zh-TW']:text-purple-500 */
.\&_div\[data-lang\=\'zh-TW\'\]\:text-purple-500 div[data-lang='zh-TW'] {
  color: #a855f7;
}
```

ORDERED LISTS - https://codepen.io/tylerforesthauser/pen/zYPpRvz
```css
/* &_ol[type='a'_s]:(list-lower-alpha bg-lime-500) */

/* &_ol[type='a'_s]:list-lower-alpha */
.\&_ol\[type\=\'a\'_s\]\:list-lower-alpha ol[type="a" s] {
  list-style-type: lower-alpha;
}

/* &_ol[type='a'_s]:bg-lime-500 */
.\&_ol\[type\=\'a\'_s\]\:bg-lime-500 ol[type="a" s] {
  background: #84cc16;
}

/* &_ol[type='A'_s]:(list-upper-alpha bg-lime-400) */

/* &_ol[type='A'_s]:list-upper-alpha */
.\&_ol\[type\=\'A\'_s\]\:list-upper-alpha ol[type="A" s] {
  list-style-type: upper-alpha;
}

/* &_ol[type='A'_s]:bg-lime-400 */
.\&_ol\[type\=\'A\'_s\]\:bg-lime-400 ol[type="A" s] {
  background: #a3e635;
}
```

And, if I'm not mistaken, pseudo classes would already be supported because you can simply chain variants.

So the other thing to consider would be support for selector lists: eg. `&_button,&_span:underline`

I could see this being useful when it comes to grouping a ton of classes that you'd have to duplicate to target a different nested element.

Anyways, I hope this is helpful and, most importantly, feasible.

Thanks!
