### ISSUE TITLE
Gradients with arbitrary color stop position

### ISSUE THREAD

**Issue by hastebrot** [tw-in-js/twind#296]
This works in Tailwind 3.0.18, but not in latest Twind v1.

```html
<p>foo <span class="bg-gradient-to-r from-[#FF0000_50%] to-[#CCCC00_85%]">foobar</span> foobarbaz</p>
```

Works on https://play.tailwindcss.com/.

Twind version: 1.0.0-next.37

Generated CSS:

```css
.to-\[\#CCCC00_85\%\] {
  --tw-gradient-to: #CCCC00 85%;
}
.from-\[\#FF0000_50\%\] {
  --tw-gradient-from: #FF0000 50%;
  --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgb(255 255 255 / 0));
}
.bg-gradient-to-r {
  background-image: linear-gradient(to right, var(--tw-gradient-stops));
}
```
