### ISSUE TITLE
generate pseudo selectors in plugin

### ISSUE THREAD

**Issue by nicolaiunrein** [tw-in-js/twind#307]
Thanks for the great library.

I'm currently migrating my tailwind code to be fully supported in twind and I'm stuck rewriting this utility into a plugin:

```css
 @layer utilities {
  @variants responsive {
    .scrollbar-none {
      -ms-overflow-style: none; 
      scrollbar-width: none; 
      scrollbar-height: none;
      scrollbar-color: transparent transparent;
    }


    /* Is it possible to generate these in plugin? <===================  */ 
    .scrollbar-none::-moz-scrollbar {
      display: none;
    }

    .scrollbar-none::-webkit-scrollbar {
      display: none;
    }
  }
}

```

Thanks in advance!
