### ISSUE TITLE
@next: Hash comments are added to CSS output from extract

### ISSUE THREAD

**Issue by rschristian** [tw-in-js/twind#313]
Strangely I cannot reproduce this on any online editor, but the local reproduction is pretty simple:

```js
import { extract, setup } from 'twind';
import presetTailwind from '@twind/preset-tailwind';

setup({
    presets: [presetTailwind()],
    hash: false,
});

const { css } = extract('<div class="mr-5"></div>');

console.log(css);
```

This results in the following (prettified) CSS output excerpt:

```css
/*!27wr28,s*/
*,
::before,
::after {
	box-sizing: border-box;
	border-width: 0;
	border-style: solid;
	border-color: #e5e7eb
}

...

/*!dbgidc,y,mr-5*/
.mr-5 {
	margin-right: 1.25rem
}
```

Not really sure where this is coming from or why. Being unable to reproduce in a browser environment makes me wonder if Node is issue in some way? Not really sure, still looking into it but I might be missing something obvious.

Correct me if I'm wrong, but as hashing has been disabled, I don't think the comments add any value or serve any purpose?
