### ISSUE TITLE
[Feature]: Tailwind will automatically add `content: ''`.

### ISSUE THREAD

**Issue by hastebrot** [tw-in-js/twind#405]
### Describe the problem

Tailwind's preflight base styles will include `content-['']` any time you use the `before` and `after` modifiers.

Documentation: https://tailwindcss.com/docs/hover-focus-and-other-states#before-and-after

- Works in Tailwind 3.2.4: https://play.tailwindcss.com/MGVcBctNEX
- Does not work in Twind 1.0.2: https://twind.run/dash-owl-morgan

![play tailwindcss com_MGVcBctNEX](https://user-images.githubusercontent.com/496255/205674572-fc05d116-44aa-4f10-87e1-b7cbd363cb90.png)

### Describe the proposed solution

It should detect when I use `before:..` and `after:...` classes and generate `content: ""`.

Tailwind does something like:

```css
.before\:absolute::before {
  content: var(--tw-content);
  position: absolute;
}
```

Twind already has 

```css
::before,
::after {
	--tw-content: "";
}
```

But does no futher things it seems.

### Alternatives considered

Define it explicitly: `<div class="before:content-[''] before:block ...">`

### Importance

nice to have
