### ISSUE TITLE
[Feature]: support vars in square brackts

### ISSUE THREAD

**Issue by s-cork** [tw-in-js/twind#507]
### Describe the problem

i want to do something like bg-[--my-var]

expected output

```css
.bg-\[--my-var\] {
    background-color: var(--my-var);
}

```

actual output 

```css
.bg-\[--my-var\] {
}

```

I also tried doing `bg-[var(--my-var)]`

but ended up with the output:

```css
.bg-\[var(--my-var\)] {
    background-image: var(--my-var);
}

```

which seems like a bug

### Describe the proposed solution

support vars like tailwind css:
https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values

### Importance

would make my life easier
